services:
  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017
    depends_on:
      - mongo

volumes:
  mongo-data:
